#!/usr/bin/env python3
"""
stamp-js 互操作性测试：用真实文件 + 独立第三方工具反向验证。

工具链：
  - Pillow 12.1     → 生成真实 JPEG/PNG 图片
  - requests        → 下载真实 MP4 视频
  - Node.js + stamp-js → 写入元数据标签
  - exiftool 13.50  → 独立读取 XMP / iTunes 元数据（第三方验证）
  - Pillow          → 重新打开图片，验证完整性
  - Python          → 手动解析 MP4 盒子结构，验证 stco 偏移

运行：python3 test/interop-test.py
"""
import subprocess
import json
import os
import shutil
import sys
import struct

STAMP_JS = os.path.join(os.path.dirname(__file__), '..', 'src', 'stamp.js')
WORKDIR = os.path.join(os.path.dirname(__file__), '..', 'tmp-interop')

# --------------------------------------------------------------------------
# Dependency guard: report a missing third-party tool clearly instead of
# crashing with a traceback halfway through (exit 2 = dependencies missing,
# distinct from 0 = pass and 1 = assertion failure).
# --------------------------------------------------------------------------
MISSING_DEPS = [t for t in ('node', 'exiftool') if shutil.which(t) is None]
try:
    import requests  # noqa: F401
except ImportError:
    MISSING_DEPS.append('requests')
try:
    from PIL import Image, ImageDraw, ImageFont  # noqa: F401
except ImportError:
    MISSING_DEPS.append('Pillow')
if MISSING_DEPS:
    print('\n\033[33mSKIP\033[0m 缺少互操作测试依赖: ' + ', '.join(MISSING_DEPS))
    print('  安装: apt-get install -y libimage-exiftool-perl python3-pil python3-requests')
    sys.exit(2)

import requests  # noqa: E402
from PIL import Image, ImageDraw, ImageFont  # noqa: E402

os.makedirs(WORKDIR, exist_ok=True)

PASS = 0
FAIL = 0

def check(name, cond, extra=''):
    global PASS, FAIL
    if cond:
        PASS += 1
        print(f'  \033[32m✓\033[0m {name}')
    else:
        FAIL += 1
        print(f'  \033[31m✗\033[0m {name}  \033[33m→ {extra}\033[0m')

def run_stamp_write(input_path, output_path, tags):
    """Call Node.js + stamp-js to write tags into a file."""
    tags_json = json.dumps(tags)
    input_size = os.path.getsize(input_path)
    script = f"""
import {{ writeTags, BlobSource }} from '{STAMP_JS}';
import fs from 'node:fs';
const blob = await fs.openAsBlob('{input_path}');
const res = await writeTags(new BlobSource(blob), {tags_json});
if (!res.ok) {{ console.error(JSON.stringify({{ok:false, error:res.report.error}})); process.exit(1); }}
const buf = Buffer.from(await res.blob.arrayBuffer());
fs.writeFileSync('{output_path}', buf);
console.log(JSON.stringify({{
  ok: true,
  inputSize: {input_size},
  outputSize: buf.length,
  bytesRead: res.report.stats.bytesRead,
  readCalls: res.report.stats.readCalls,
  strategy: res.report.strategy,
  notes: res.report.notes,
  warnings: res.report.warnings,
  probe: res.report.probe
}}));
"""
    result = subprocess.run(['node', '--input-type=module', '-e', script],
                          capture_output=True, text=True, timeout=30)
    if result.returncode != 0:
        return json.loads(result.stderr.strip() if result.stderr.strip() else '{"ok":false}')
    return json.loads(result.stdout.strip())

def exiftool_read(path):
    """Use exiftool to read metadata as JSON."""
    result = subprocess.run(['exiftool', '-j', '-G', path],
                          capture_output=True, text=True, timeout=15)
    if result.returncode != 0:
        return None
    data = json.loads(result.stdout)
    return data[0] if data else None


print('\n\033[1m▌ A. JPEG: Pillow 生成 → stamp-js 写入 → exiftool 验证\033[0m\n')

# 1. 生成真实 JPEG
jpg_path = os.path.join(WORKDIR, 'test.jpg')
jpg_out = os.path.join(WORKDIR, 'test_tagged.jpg')
img = Image.new('RGB', (800, 600), (30, 60, 90))
draw = ImageDraw.Draw(img)
for i in range(0, 800, 40):
    draw.line([(i, 0), (i, 600)], fill=(255, 128, 0), width=2)
for j in range(0, 600, 40):
    draw.line([(0, j), (800, j)], fill=(0, 200, 200), width=2)
draw.ellipse([200, 150, 600, 450], fill=(255, 255, 0), outline=(255, 0, 0), width=3)
draw.text((280, 280), 'JPEG TEST', fill=(255, 255, 255))
img.save(jpg_path, 'JPEG', quality=85)
check(f'Pillow 生成 JPEG ({os.path.getsize(jpg_path)} bytes)', os.path.getsize(jpg_path) > 0)

# 2. stamp-js 写入
tags = {
    'title': 'Interop Test JPEG',
    'artist': 'stamp-js Verification',
    'date': '2025-01-20T12:00:00Z',
    'comment': 'Generated by Pillow, tagged by stamp-js, verified by exiftool',
    'url': 'https://example.com/interop',
    'software': 'stamp/0.1.0',
}
res = run_stamp_write(jpg_path, jpg_out, tags)
check('stamp-js 写入成功', res.get('ok'), res.get('error', ''))
if res.get('ok'):
    check(f'输出大小 {res["outputSize"]} > 输入 {res["inputSize"]}', res['outputSize'] > res['inputSize'])
    check(f'只读了 {res["bytesRead"]} 字节', res['bytesRead'] > 0)

    # 3. exiftool 独立验证
    meta = exiftool_read(jpg_out)
    if meta:
        xmp_title = meta.get('XMP:Title', '')
        xmp_creator = meta.get('XMP:Creator', '')
        xmp_desc = meta.get('XMP:Description', '')
        xmp_source = meta.get('XMP:Source', '')
        xmp_rights = meta.get('XMP:Rights', '')
        xmp_create_date = meta.get('XMP:CreateDate', '')
        xmp_tool = meta.get('XMP:CreatorTool', '')
        check(f'exiftool 读到 XMP Title = "{xmp_title}"', xmp_title == tags['title'], f'got "{xmp_title}"')
        check(f'exiftool 读到 XMP Creator = "{xmp_creator}"', xmp_creator == tags['artist'])
        check(f'exiftool 读到 XMP Description 包含 comment', tags['comment'] in xmp_desc if xmp_desc else False)
        check(f'exiftool 读到 XMP Source = URL', xmp_source == tags['url'])
        check(f'exiftool 读到 XMP CreateDate (exiftool reformats to YYYY:MM:DD)', '2025:01:20' in xmp_create_date, f'got "{xmp_create_date}"')
        check(f'exiftool 读到 XMP CreatorTool = "{xmp_tool}"', xmp_tool == tags['software'])
    else:
        check('exiftool 读取成功', False, 'exiftool failed')

    # 4. Pillow 重新打开，验证图片完整性（重新加载原始文件比较）
    img_orig = Image.open(jpg_path)
    img2 = Image.open(jpg_out)
    check(f'Pillow 重新打开 JPEG: {img2.size} {img2.format}', img2.size == (800, 600) and img2.format == 'JPEG')
    px_orig = img_orig.load()
    px_new = img2.load()
    same = all(px_orig[x, y] == px_new[x, y] for x in range(0, 800, 100) for y in range(0, 600, 100))
    check('像素数据逐点一致（抽样）', same)

    # 5. 幂等
    res2 = run_stamp_write(jpg_out, os.path.join(WORKDIR, 'test_tagged2.jpg'), tags)
    if res2.get('ok'):
        check('幂等：第二次写入大小一致', res2['outputSize'] == res['outputSize'],
              f'{res2["outputSize"]} vs {res["outputSize"]}')


print('\n\033[1m▌ B. PNG: Pillow 生成 → stamp-js 写入 → exiftool 验证\033[0m\n')

# 1. 生成真实 PNG
png_path = os.path.join(WORKDIR, 'test.png')
png_out = os.path.join(WORKDIR, 'test_tagged.png')
img = Image.new('RGBA', (640, 480), (20, 40, 60, 255))
draw = ImageDraw.Draw(img)
for i in range(50):
    import random
    random.seed(42)
    x, y = random.randint(0, 640), random.randint(0, 480)
    r, g, b = random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)
    draw.ellipse([x-20, y-20, x+20, y+20], fill=(r, g, b, 200))
draw.text((250, 220), 'PNG TEST', fill=(255, 255, 255, 255))
img.save(png_path, 'PNG')
check(f'Pillow 生成 PNG ({os.path.getsize(png_path)} bytes)', os.path.getsize(png_path) > 0)

# 2. stamp-js 写入
res = run_stamp_write(png_path, png_out, tags)
check('stamp-js 写入成功', res.get('ok'), res.get('error', ''))
if res.get('ok'):
    check(f'输出大小 {res["outputSize"]} > 输入 {res["inputSize"]}', res['outputSize'] > res['inputSize'])

    # 3. exiftool 验证
    meta = exiftool_read(png_out)
    if meta:
        check(f'exiftool 读到 PNG XMP Title', meta.get('XMP:Title', '') == tags['title'])
        check(f'exiftool 读到 PNG XMP Creator', meta.get('XMP:Creator', '') == tags['artist'])
        # PNG text chunks
        png_title = meta.get('PNG:Title', '')
        png_author = meta.get('PNG:Author', '')
        check(f'exiftool 读到 PNG Title text chunk', png_title == tags['title'], f'got "{png_title}"')
        check(f'exiftool 读到 PNG Author text chunk', png_author == tags['artist'], f'got "{png_author}"')

    # 4. Pillow 完整性（重新加载原始文件比较）
    img_orig = Image.open(png_path)
    img2 = Image.open(png_out)
    check(f'Pillow 重新打开 PNG: {img2.size} {img2.format}', img2.size == (640, 480) and img2.format == 'PNG')
    px_orig = img_orig.load()
    px_new = img2.load()
    same = all(px_orig[x, y] == px_new[x, y] for x in range(0, 640, 80) for y in range(0, 480, 80))
    check('像素数据逐点一致（抽样）', same)


print('\n\033[1m▌ C. MP4: 下载真实视频 → stamp-js 写入 → exiftool + 手动解析验证\033[0m\n')

# 1. 下载真实 MP4
mp4_path = os.path.join(WORKDIR, 'test.mp4')
mp4_out = os.path.join(WORKDIR, 'test_tagged.mp4')
download_ok = False
try:
    print('  下载 sample-5s.mp4 ...')
    resp = requests.get('https://download.samplelib.com/mp4/sample-5s.mp4', timeout=30)
    resp.raise_for_status()
    with open(mp4_path, 'wb') as f:
        f.write(resp.content)
    if os.path.getsize(mp4_path) > 100000:
        download_ok = True
        check(f'下载真实 MP4 ({os.path.getsize(mp4_path)} bytes)', True)
except Exception as e:
    print(f'  \033[33m\u26a0 网络不可用 ({type(e).__name__})，回退到本地构造的 MP4\033[0m')

if not download_ok:
    # Fallback: build a real-structure MP4 locally (no network)
    subprocess.run(['node', '-e', f"""
import * as F from './test/fixtures.mjs';
import fs from 'node:fs';
const fx = F.buildMp4({{ layout: 'head', chunks: 8, chunkSize: 4096 }});
fs.writeFileSync('{mp4_path}', Buffer.from(fx.bytes));
"""], cwd=os.path.dirname(__file__) + '/..', capture_output=True, text=True, timeout=10,
        env={**os.environ, 'NODE_PATH': '.'})
    check(f'本地构造 MP4 ({os.path.getsize(mp4_path)} bytes)', os.path.getsize(mp4_path) > 0)

# 2. exiftool 读取原始文件信息
meta_before = exiftool_read(mp4_path)
if meta_before:
    print(f'  原始文件: {meta_before.get("QuickTime:MajorBrand", "?")}, '
          f'{meta_before.get("File:FileSize", "?")} bytes')

# 3. stamp-js 写入
mp4_tags = {
    'title': 'Interop MP4 Test',
    'artist': 'stamp-js Verification',
    'comment': 'Real MP4 from samplelib.com, tagged by stamp-js',
    'date': '2025-01-20T12:00:00Z',
    'software': 'stamp/0.1.0',
}
res = run_stamp_write(mp4_path, mp4_out, mp4_tags)
check('stamp-js 写入成功', res.get('ok'), res.get('error', ''))
if res.get('ok'):
    check(f'输出大小 {res["outputSize"]} > 输入 {res["inputSize"]}', res['outputSize'] >= res['inputSize'])
    check(f'只读了 {res["bytesRead"]} 字节（< 1MB）', res['bytesRead'] < 1024*1024,
          f'bytesRead={res["bytesRead"]}')
    check(f'strategy = {res.get("strategy", "?")}', bool(res.get('strategy')))

    # 4. exiftool 独立验证 MP4 元数据
    meta_after = exiftool_read(mp4_out)
    if meta_after:
        title = meta_after.get('QuickTime:Title', '') or meta_after.get('MP4:Title', '')
        artist = meta_after.get('QuickTime:Artist', '') or meta_after.get('MP4:Artist', '')
        comment = meta_after.get('QuickTime:Comment', '') or meta_after.get('MP4:Comment', '')
        check(f'exiftool 读到 MP4 Title = "{title}"', title == mp4_tags['title'], f'got "{title}"')
        check(f'exiftool 读到 MP4 Artist = "{artist}"', artist == mp4_tags['artist'], f'got "{artist}"')
        check(f'exiftool 读到 MP4 Comment', mp4_tags['comment'] in comment if comment else False, f'got "{comment}"')

    # 5. 手动解析 MP4 盒子结构
    with open(mp4_out, 'rb') as f:
        data = f.read()

    def u32(b, o):
        return struct.unpack('>I', b[o:o+4])[0]

    def fourcc(b, o):
        return b[o:o+4].decode('ascii', errors='replace')

    boxes = []
    pos = 0
    while pos + 8 <= len(data):
        size = u32(data, pos)
        hdr = 8
        tp = fourcc(data, pos + 4)
        if size == 1:
            size = struct.unpack('>Q', data[pos+8:pos+16])[0]
            hdr = 16
        elif size == 0:
            size = len(data) - pos
        if size < hdr or pos + size > len(data):
            break
        boxes.append((tp, size, pos))
        pos += size

    check(f'顶层盒子结构完整（{len(boxes)} 个）', len(boxes) > 0)
    print(f'    盒子: {", ".join(b[0] for b in boxes)}')

    # 找 moov
    moov = next((b for b in boxes if b[0] == 'moov'), None)
    if moov:
        check('moov 盒子存在', True)
        moov_data = data[moov[2]:moov[2]+moov[1]]
        # 找 udta
        p = 8
        udta_found = False
        while p + 8 <= len(moov_data):
            sz = u32(moov_data, p)
            tp = fourcc(moov_data, p + 4)
            if tp == 'udta':
                udta_found = True
                # 找 meta
                mp = p + 8
                while mp + 8 < p + sz:
                    msz = u32(moov_data, mp)
                    mtp = fourcc(moov_data, mp + 4)
                    if mtp == 'meta':
                        # 找 hdlr
                        kp = mp + 12
                        while kp + 8 < mp + msz:
                            ksz = u32(moov_data, kp)
                            ktp = fourcc(moov_data, kp + 4)
                            if ktp == 'hdlr':
                                hdlr_type = fourcc(moov_data, kp + 16)
                                check(f'meta/hdlr = {hdlr_type}', hdlr_type in ('mdir', 'mdta'))
                            if ktp == 'ilst':
                                # 读 ilst 条目
                                ip = kp + 8
                                entries = []
                                while ip + 8 < kp + ksz:
                                    isz = u32(moov_data, ip)
                                    iname = fourcc(moov_data, ip + 4)
                                    # 读 data 盒
                                    dp = ip + 8
                                    if dp + 16 <= ip + isz:
                                        dsz = u32(moov_data, dp)
                                        if fourcc(moov_data, dp + 4) == 'data' and dsz >= 16:
                                            val = moov_data[dp+16:dp+dsz].decode('utf-8', errors='replace')
                                            entries.append((iname.replace('\xa9', '©'), val[:40]))
                                    ip += isz
                                check(f'ilst 有 {len(entries)} 个条目', len(entries) >= 2)
                                for name, val in entries:
                                    print(f'      {name} = {val}')
                                    if name == '©nam':
                                        check(f'©nam = "{val}" == title', val == mp4_tags['title'])
                                    if name == '©ART':
                                        check(f'©ART = "{val}" == artist', val == mp4_tags['artist'])
                            kp += ksz
                    mp += msz
                break
            p += sz
        check('udta 盒子存在', udta_found)

    # 6. 验证 mdat 数据完整性（首尾字节）
    mdat_orig = next((b for b in boxes if b[0] == 'mdat'), None)
    if mdat_orig:
        # 读取原始文件的 mdat
        with open(mp4_path, 'rb') as f:
            orig_data = f.read()
        orig_mdat = None
        op = 0
        while op + 8 <= len(orig_data):
            sz = u32(orig_data, op)
            tp = fourcc(orig_data, op + 4)
            if sz == 1: sz = struct.unpack('>Q', orig_data[op+8:op+16])[0]
            elif sz == 0: sz = len(orig_data) - op
            if tp == 'mdat':
                orig_mdat = (op, sz)
                break
            op += sz
        if orig_mdat:
            # 比较 mdat 的前 1000 和后 1000 字节
            out_mdat_start = mdat_orig[2] + 8
            orig_mdat_start = orig_mdat[0] + 8
            mdat_len = min(mdat_orig[1] - 8, orig_mdat[1] - 8)
            head_match = data[out_mdat_start:out_mdat_start+1000] == orig_data[orig_mdat_start:orig_mdat_start+1000]
            tail_out = out_mdat_start + mdat_len - 1000
            tail_orig = orig_mdat_start + mdat_len - 1000
            tail_match = data[tail_out:tail_out+1000] == orig_data[tail_orig:tail_orig+1000]
            check('mdat 头部 1000 字节一致', head_match)
            check('mdat 尾部 1000 字节一致', tail_match)

    # 7. 幂等
    res2 = run_stamp_write(mp4_out, os.path.join(WORKDIR, 'test_tagged2.mp4'), mp4_tags)
    if res2.get('ok'):
        check('幂等：第二次写入大小一致', res2['outputSize'] == res['outputSize'],
              f'{res2["outputSize"]} vs {res["outputSize"]}')


# 清理
import shutil
shutil.rmtree(WORKDIR, ignore_errors=True)

print(f'\n\033[1m{"ALL PASSED" if FAIL == 0 else "SOME FAILED"}\033[0m  {PASS} passed, {FAIL} failed\n')
sys.exit(0 if FAIL == 0 else 1)
