/**
 * Build script: converts src/stamp.js (ESM) to dist/stamp.umd.js (UMD).
 *
 * No bundler dependency — uses simple text transformation:
 *   1. Strip `export ` prefixes (function/class/const/async function)
 *   2. Strip `export default {...}` line
 *   3. Wrap in UMD boilerplate
 *   4. Append return statement with all exported names
 *
 * Run: node scripts/build-umd.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const srcPath = path.join(__dirname, '..', 'src', 'stamp.js');
const outDir = path.join(__dirname, '..', 'dist');
const outPath = path.join(outDir, 'stamp.umd.js');

const src = fs.readFileSync(srcPath, 'utf8');

// Collect all exported names
const exportNames = [];
const exportRegex = /^export\s+(?:default\s+)?(?:async\s+)?(?:function|class|const)\s+(\w+)/gm;
let m;
while ((m = exportRegex.exec(src)) !== null) {
  if (m[1] !== 'default') exportNames.push(m[1]);
}
// Also catch `export const A = ..., B = ...` multi-declarations (not present, but safe)

// Strip `export ` and `export default {...}` lines
let body = src
  .replace(/^export\s+(async\s+function\s)/gm, '$1')
  .replace(/^export\s+(function\s)/gm, '$1')
  .replace(/^export\s+(class\s)/gm, '$1')
  .replace(/^export\s+(const\s)/gm, '$1')
  .replace(/^export\s+default\s+\{[^}]*\};?\s*$/gm, '');

const umd = `/**
 * stamp-js UMD build (auto-generated from src/stamp.js)
 * Do not edit this file directly — run: node scripts/build-umd.mjs
 */
(function (global, factory) {
  if (typeof exports === 'object' && typeof module !== 'undefined') module.exports = factory();
  else if (typeof define === 'function' && define.amd) define(factory);
  else (global || self).stamp = factory();
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

${body}

  return { ${exportNames.join(', ')} };
});
`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outPath, umd);
console.log(`Built ${outPath} (${exportNames.length} exports: ${exportNames.join(', ')})`);
